In [431]:
import keras

In [432]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [433]:
data=pd.read_csv("C:/Users/Anubhav Sanyal/Desktop/Deep Leaning/Artificial_Neural_Networks/Churn_Modelling.csv")

In [434]:
data

RowNumber  CustomerId         Surname  CreditScore Geography  Gender  \
0             1    15634602        Hargrave          619    France  Female   
1             2    15647311            Hill          608     Spain  Female   
2             3    15619304            Onio          502    France  Female   
3             4    15701354            Boni          699    France  Female   
4             5    15737888        Mitchell          850     Spain  Female   
5             6    15574012             Chu          645     Spain    Male   
6             7    15592531        Bartlett          822    France    Male   
7             8    15656148          Obinna          376   Germany  Female   
8             9    15792365              He          501    France    Male   
9            10    15592389              H?          684    France    Male   
10           11    15767821          Bearce          528    France    Male   
11           12    15737173         Andrews          497     Spain    Male   
12           13    15632264             Kay          476    France  Female   
13           14    15691483            Chin          549    France  Female   
14           15    15600882           Scott          635     Spain  Female   
15           16    15643966         Goforth          616   Germany    Male   
16           17    15737452           Romeo          653   Germany    Male   
17           18    15788218       Henderson          549     Spain  Female   
18           19    15661507         Muldrow          587     Spain    Male   
19           20    15568982             Hao          726    France  Female   
20           21    15577657        McDonald          732    France    Male   
21           22    15597945        Dellucci          636     Spain  Female   
22           23    15699309       Gerasimov          510     Spain  Female   
23           24    15725737          Mosman          669    France    Male   
24           25    15625047             Yen          846    France  Female   
25           26    15738191         Maclean          577    France    Male   
26           27    15736816           Young          756   Germany    Male   
27           28    15700772         Nebechi          571    France    Male   
28           29    15728693      McWilliams          574   Germany  Female   
29           30    15656300        Lucciano          411    France    Male   
...         ...         ...             ...          ...       ...     ...   
9970       9971    15587133        Thompson          518    France    Male   
9971       9972    15721377            Chou          833    France  Female   
9972       9973    15747927           Ch'in          758    France    Male   
9973       9974    15806455          Miller          611    France    Male   
9974       9975    15695474          Barker          583    France    Male   
9975       9976    15666295           Smith          610   Germany    Male   
9976       9977    15656062         Azikiwe          637    France  Female   
9977       9978    15579969         Mancini          683    France  Female   
9978       9979    15703563           P'eng          774    France    Male   
9979       9980    15692664          Diribe          677    France  Female   
9980       9981    15719276            T'ao          741     Spain    Male   
9981       9982    15672754        Burbidge          498   Germany    Male   
9982       9983    15768163         Griffin          655   Germany  Female   
9983       9984    15656710           Cocci          613    France    Male   
9984       9985    15696175  Echezonachukwu          602   Germany    Male   
9985       9986    15586914          Nepean          659    France    Male   
9986       9987    15581736        Bartlett          673   Germany    Male   
9987       9988    15588839         Mancini          606     Spain    Male   
9988       9989    15589329         Pirozzi          775    France    Male   
9989       9990    15605622 

In [435]:
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [436]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
5             645     Spain    Male   44       8  113755.78              2   
6             822    France    Male   50       7       0.00              2   
7             376   Germany  Female   29       4  115046.74              4   
8             501    France    Male   44       4  142051.07              2   
9             684    France    Male   27       2  134603.88              1   
10            528    France    Male   31       6  102016.72              2   
11            497     Spain    Male   24       3       0.00              2   
12            476    France  Female   34      10       0.00              2   
13            549    France  Female   25       5       0.00              2   
14            635     Spain  Female   35       7       0.00              2   
15            616   Germany    Male   45       3  143129.41              2   
16            653   Germany    Male   58       1  132602.88              1   
17            549     Spain  Female   24       9       0.00              2   
18            587     Spain    Male   45       6       0.00              1   
19            726    France  Female   24       6       0.00              2   
20            732    France    Male   41       8       0.00              2   
21            636     Spain  Female   32       8       0.00              2   
22            510     Spain  Female   38       4       0.00              1   
23            669    France    Male   46       3       0.00              2   
24            846    France  Female   38       5       0.00              1   
25            577    France    Male   25       3       0.00              2   
26            756   Germany    Male   36       2  136815.64              1   
27            571    France    Male   44       9       0.00              2   
28            574   Germany  Female   43       3  141349.43              1   
29            411    France    Male   29       0   59697.17              2   
...           ...       ...     ...  ...     ...        ...            ...   
9970          518    France    Male   42       7  151027.05              2   
9971          833    France  Female   34       3  144751.81              1   
9972          758    France    Male   26       4  155739.76              1   
9973          611    France    Male   27       7       0.00              2   
9974          583    France    Male   33       7  122531.86              1   
9975          610   Germany    Male   50       1  113957.01              2   
9976          637    France  Female   33       7  103377.81              1   
9977          683    France  Female   32       9       0.00              2   
9978          774    France    Male   40       9   93017.47              2   
9979          677    France  Female   58       1   90022.85              1   
9980          741     Spain    Male   35       6   74371.49              1   
9981          498   Germany    Male   42       3  152039.70              1   
9982          655   Germany  Female   46       7  137145.12              1   
9983          613    France    Male   40       4       0.00              1   
9984          602   Germany    Male   35       7   90602.42              2   
9985          659    France    Male   36       6  123841.49              2   
9986          673   Germany    Male   47       1  183579.54              2   
9987          606     Spain    Male   30       8  180307.73              2   
9988          775    France    Male   30       4       0.00              2   
9989          841     Spain 

In [437]:
data.Geography[data.Geography=="France"]=1
data.Geography[data.Geography=="Spain"]=2
data.Geography[data.Geography=="Germany"]=3


C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing import

In [438]:
data.Gender[data.Gender=="Female"]=0
data.Gender[data.Gender=="Male"]=1

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [439]:
data

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0             619         1      0   42       2       0.00              1   
1             608         2      0   41       1   83807.86              1   
2             502         1      0   42       8  159660.80              3   
3             699         1      0   39       1       0.00              2   
4             850         2      0   43       2  125510.82              1   
5             645         2      1   44       8  113755.78              2   
6             822         1      1   50       7       0.00              2   
7             376         3      0   29       4  115046.74              4   
8             501         1      1   44       4  142051.07              2   
9             684         1      1   27       2  134603.88              1   
10            528         1      1   31       6  102016.72              2   
11            497         2      1   24       3       0.00              2   
12            476         1      0   34      10       0.00              2   
13            549         1      0   25       5       0.00              2   
14            635         2      0   35       7       0.00              2   
15            616         3      1   45       3  143129.41              2   
16            653         3      1   58       1  132602.88              1   
17            549         2      0   24       9       0.00              2   
18            587         2      1   45       6       0.00              1   
19            726         1      0   24       6       0.00              2   
20            732         1      1   41       8       0.00              2   
21            636         2      0   32       8       0.00              2   
22            510         2      0   38       4       0.00              1   
23            669         1      1   46       3       0.00              2   
24            846         1      0   38       5       0.00              1   
25            577         1      1   25       3       0.00              2   
26            756         3      1   36       2  136815.64              1   
27            571         1      1   44       9       0.00              2   
28            574         3      0   43       3  141349.43              1   
29            411         1      1   29       0   59697.17              2   
...           ...       ...    ...  ...     ...        ...            ...   
9970          518         1      1   42       7  151027.05              2   
9971          833         1      0   34       3  144751.81              1   
9972          758         1      1   26       4  155739.76              1   
9973          611         1      1   27       7       0.00              2   
9974          583         1      1   33       7  122531.86              1   
9975          610         3      1   50       1  113957.01              2   
9976          637         1      0   33       7  103377.81              1   
9977          683         1      0   32       9       0.00              2   
9978          774         1      1   40       9   93017.47              2   
9979          677         1      0   58       1   90022.85              1   
9980          741         2      1   35       6   74371.49              1   
9981          498         3      1   42       3  152039.70              1   
9982          655         3      0   46       7  137145.12              1   
9983          613         1      1   40       4       0.00              1   
9984          602         3      1   35       7   90602.42              2   
9985          659         1      1   36       6  123841.49              2   
9986          673         3      1   47       1  183579.54              2   
9987          606         2      1   30       8  180307.73              2   
9988          775         1      1   30       4       0.00              2   
9989          841         2      1   28       4       0.00              2   
99

In [440]:
X=data.iloc[:,0:10]

In [441]:
X

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0             619         1      0   42       2       0.00              1   
1             608         2      0   41       1   83807.86              1   
2             502         1      0   42       8  159660.80              3   
3             699         1      0   39       1       0.00              2   
4             850         2      0   43       2  125510.82              1   
5             645         2      1   44       8  113755.78              2   
6             822         1      1   50       7       0.00              2   
7             376         3      0   29       4  115046.74              4   
8             501         1      1   44       4  142051.07              2   
9             684         1      1   27       2  134603.88              1   
10            528         1      1   31       6  102016.72              2   
11            497         2      1   24       3       0.00              2   
12            476         1      0   34      10       0.00              2   
13            549         1      0   25       5       0.00              2   
14            635         2      0   35       7       0.00              2   
15            616         3      1   45       3  143129.41              2   
16            653         3      1   58       1  132602.88              1   
17            549         2      0   24       9       0.00              2   
18            587         2      1   45       6       0.00              1   
19            726         1      0   24       6       0.00              2   
20            732         1      1   41       8       0.00              2   
21            636         2      0   32       8       0.00              2   
22            510         2      0   38       4       0.00              1   
23            669         1      1   46       3       0.00              2   
24            846         1      0   38       5       0.00              1   
25            577         1      1   25       3       0.00              2   
26            756         3      1   36       2  136815.64              1   
27            571         1      1   44       9       0.00              2   
28            574         3      0   43       3  141349.43              1   
29            411         1      1   29       0   59697.17              2   
...           ...       ...    ...  ...     ...        ...            ...   
9970          518         1      1   42       7  151027.05              2   
9971          833         1      0   34       3  144751.81              1   
9972          758         1      1   26       4  155739.76              1   
9973          611         1      1   27       7       0.00              2   
9974          583         1      1   33       7  122531.86              1   
9975          610         3      1   50       1  113957.01              2   
9976          637         1      0   33       7  103377.81              1   
9977          683         1      0   32       9       0.00              2   
9978          774         1      1   40       9   93017.47              2   
9979          677         1      0   58       1   90022.85              1   
9980          741         2      1   35       6   74371.49              1   
9981          498         3      1   42       3  152039.70              1   
9982          655         3      0   46       7  137145.12              1   
9983          613         1      1   40       4       0.00              1   
9984          602         3      1   35       7   90602.42              2   
9985          659         1      1   36       6  123841.49              2   
9986          673         3      1   47       1  183579.54              2   
9987          606         2      1   30       8  180307.73              2   
9988          775         1      1   30       4       0.00              2   
9989          841         2      1   28       4       0.00              2   
99

In [442]:
y=data.iloc[:,10]

In [443]:
y

0       1
1       0
2       1
3       0
4       0
5       1
6       0
7       1
8       0
9       0
10      0
11      0
12      0
13      0
14      0
15      0
16      1
17      0
18      0
19      0
20      0
21      0
22      1
23      0
24      0
25      0
26      0
27      0
28      0
29      0
       ..
9970    0
9971    0
9972    0
9973    0
9974    0
9975    1
9976    0
9977    0
9978    0
9979    0
9980    0
9981    1
9982    1
9983    0
9984    0
9985    0
9986    0
9987    0
9988    0
9989    0
9990    0
9991    1
9992    0
9993    0
9994    0
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [392]:
X=X.values

In [393]:
y=y.values

In [444]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=100)

In [445]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [368]:
X=X.values
y=y.values

In [446]:
from keras.models import Sequential

In [447]:
from keras.layers import Dense

In [448]:
classifier=Sequential()

In [449]:
classifier.add(Dense(units=6,init="uniform",activation="relu",input_dim=10))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, activation="relu", input_dim=10, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [450]:
classifier.add(Dense(output_dim=6,init="uniform",activation="relu"))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [451]:
classifier.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [452]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [453]:
classifier.fit(X_train,y_train,batch_size=32,nb_epoch=55)


C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/55
8000/8000 [==============================] - 4s 489us/step - loss: 0.5849 - acc: 0.7969
Epoch 2/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.4367 - acc: 0.7969
Epoch 3/55
8000/8000 [==============================] - 1s 118us/step - loss: 0.4280 - acc: 0.7969
Epoch 4/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.4235 - acc: 0.7969
Epoch 5/55
8000/8000 [==============================] - 1s 117us/step - loss: 0.4183 - acc: 0.8177
Epoch 6/55
8000/8000 [==============================] - 1s 128us/step - loss: 0.4124 - acc: 0.8346
Epoch 7/55
8000/8000 [==============================] - 1s 122us/step - loss: 0.4082 - acc: 0.8346
Epoch 8/55
8000/8000 [==============================] - 1s 121us/step - loss: 0.4050 - acc: 0.8356
Epoch 9/55
8000/8000 [==============================] - 1s 120us/step - loss: 0.4027 - acc: 0.8359
Epoch 10/55
8000/8000 [==============================] - 1s 127us/step - loss: 0.4011 - acc: 0.8356 1s - loss

AttributeError: 'StandardScaler' object has no attribute 'values'

In [454]:
classifier.predict(X_test)

array([[0.05228662],
       [0.15278786],
       [0.14449745],
       ...,
       [0.05920535],
       [0.05272087],
       [0.05465016]], dtype=float32)

In [458]:
t.shape

(3000, 1)

In [455]:
t=t>0.5

In [456]:
t

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [459]:
y_test.shape

(2000,)

In [276]:
pred=[]
for i in range(3000):
    k=t[i]
    pred.append(k)

In [277]:
pred.unique

AttributeError: 'list' object has no attribute 'unique'

In [278]:
pred

[array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=float32),
 array([0.1981166], dtype=fl

In [461]:
from sklearn.metrics import confusion_matrix
cf=confusion_matrix(t[0:2000],y_test)

In [462]:
cf

array([[1588,  412],
       [   0,    0]], dtype=int64)