In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
import keras

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
data_x=pd.read_csv('C:/Users/Anubhav Sanyal/Desktop/Deep Learning Summer of ML-CodingBlocks/ANN/Logistic_X_Train.csv')

In [5]:
data_y=pd.read_csv('C:/Users/Anubhav Sanyal/Desktop/Deep Learning Summer of ML-CodingBlocks/ANN/Logistic_Y_Train.csv')

In [6]:
data_x.shape

(2250, 2)

In [7]:
data_y.shape

(2250, 1)

In [10]:
data_x=data_x.values

In [11]:
data_y=data_y.values

In [25]:
data_y=data_y.reshape((2250,))

In [26]:
data_y.shape

(2250,)

In [28]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(data_x)
sc.transform(data_y.reshape(-1,1))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


ValueError: non-broadcastable output operand with shape (2250,1) doesn't match the broadcast shape (2250,2)

In [29]:
from keras.models import Sequential

In [30]:
from keras.layers import Dense

In [31]:
classifier=Sequential()

In [32]:
classifier.add(Dense(output_dim=2,init="uniform",activation="relu",input_dim=2))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=2, units=2, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [33]:
classifier.add(Dense(output_dim=1,init="uniform",activation="sigmoid"))

C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.


In [34]:
classifier.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [36]:
classifier.fit(data_x,data_y,batch_size=32,nb_epoch=10)

Instructions for updating:
Use tf.cast instead.


C:\Users\Anubhav Sanyal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/10
2250/2250 [==============================] - 1s 454us/step - loss: 0.6930 - acc: 0.4933
Epoch 2/10
2250/2250 [==============================] - 0s 100us/step - loss: 0.6884 - acc: 0.5018
Epoch 3/10
2250/2250 [==============================] - 0s 94us/step - loss: 0.6755 - acc: 0.5484
Epoch 4/10
2250/2250 [==============================] - 0s 78us/step - loss: 0.6562 - acc: 0.8027
Epoch 5/10
2250/2250 [==============================] - 0s 80us/step - loss: 0.6327 - acc: 0.8111
Epoch 6/10
2250/2250 [==============================] - 0s 84us/step - loss: 0.6075 - acc: 0.8213
Epoch 7/10
2250/2250 [==============================] - 0s 92us/step - loss: 0.5826 - acc: 0.8253
Epoch 8/10
2250/2250 [==============================] - 0s 105us/step - loss: 0.5590 - acc: 0.8293
Epoch 9/10
2250/2250 [==============================] - 0s 106us/step - loss: 0.5371 - acc: 0.8369
Epoch 10/10
2250/2250 [==============================] - 0s 84us/step - loss: 0.5168 - acc: 0.8396


In [37]:
data_test=pd.read_csv('C:/Users/Anubhav Sanyal/Desktop/Deep Learning Summer of ML-CodingBlocks/ANN/Logistic_X_Test (1).csv')

In [49]:
t=classifier.predict(data_test)

In [39]:
t

array([[0.3166318 ],
       [0.15364105],
       [0.57934195],
       [0.25736624],
       [0.57934195],
       [0.44380942],
       [0.42549667],
       [0.14505002],
       [0.4443607 ],
       [0.32197517],
       [0.51874006],
       [0.57934195],
       [0.19357985],
       [0.57934195],
       [0.52606195],
       [0.55322564],
       [0.27852565],
       [0.18387753],
       [0.57934195],
       [0.2860624 ],
       [0.21908113],
       [0.51594454],
       [0.57934195],
       [0.18602714],
       [0.57934195],
       [0.22765812],
       [0.21920061],
       [0.2811913 ],
       [0.34848657],
       [0.3408378 ],
       [0.538262  ],
       [0.27332193],
       [0.57934195],
       [0.4911175 ],
       [0.30715358],
       [0.57934195],
       [0.57934195],
       [0.21404698],
       [0.38999683],
       [0.57934195],
       [0.2900355 ],
       [0.36886477],
       [0.23271528],
       [0.57934195],
       [0.56181705],
       [0.3249733 ],
       [0.57934195],
       [0.579

In [40]:
t.shape

(750, 1)

In [52]:
for i in range(750):
    if(t[i]>=0.5):
        t[i]=1
    else:
        t[i]=0

In [57]:
t

array([[0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],

In [62]:
t=t.reshape((750,))

In [64]:
t

array([0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1.,
       1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 1., 1., 0., 1.

In [45]:
k=[]
for i in range(750):
    p=t[i]
    k.append(p)

In [46]:
k

[array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([1.], dtype=float32),
 array([0.], dtype=float32),
 array([0.], d

In [43]:
import csv

In [59]:
import csv



with open('C:/Users/Anubhav Sanyal/Desktop/Deep Learning Summer of ML-CodingBlocks/ANN/prediction.csv', 'w') as csvFile:
    writer = csv.writer(csvFile)
    writer.writerows([t])

csvFile.close()